---
title: "Suivi"
author: "Noe Guinko"
date: "30/11/2020"
output: html_document
---

```{r}
library(readxl)
sui <- read_excel("~/GOMA CA SURV/My R scripts/sui.xlsx")
```


Recoder les colonnes pour une analyse plus facile

```{r}
sui<-rename(sui,  Rendezvous1="Rendezvous 1",
                  Rendezvous2="Rendezvous 2",
                  Rendezvous3="Rendezvous 3",
                  Rendezvous4="Rendezvous 4",
                  Rendezvous5="Rendezvous 5",
                  Rendezvous6="Rendezvous 6",
                  Rendezvous7="Rendezvous 7",
                  Rendezvous8="Rendezvous 8",
                  visite1="visite 1",
                  visite2="visite 2",
                  visite3="visite 3",
                  visite4="visite 4",
                  visite5="visite 5",
                  visite6="visite 6",
                  visite7="visite 7",
                  visite8="visite 8",
            
            )
```



Se rassurer que les formats des dates utilisés est correct

```{r}

sui$Rendezvous1<-as.Date(sui$Rendezvous1, "%d/%m/%Y")
sui$Rendezvous2<-as.Date(sui$Rendezvous2, "%d/%m/%Y")
sui$Rendezvous3<-as.Date(sui$Rendezvous3, "%d/%m/%Y")
sui$Rendezvous4<-as.Date(sui$Rendezvous4, "%d/%m/%Y")
sui$Rendezvous5<-as.Date(sui$Rendezvous5, "%d/%m/%Y")
sui$Rendezvous6<-as.Date(sui$Rendezvous6, "%d/%m/%Y")
sui$Rendezvous7<-as.Date(sui$Rendezvous7, "%d/%m/%Y")
sui$Rendezvous8<-as.Date(sui$Rendezvous8, "%d/%m/%Y")

sui$visite1<-as.Date(sui$visite1, "%d/%m/%Y")
sui$visite2<-as.Date(sui$visite2, "%d/%m/%Y")
sui$visite3<-as.Date(sui$visite3, "%d/%m/%Y")
sui$visite4<-as.Date(sui$visite4, "%d/%m/%Y")
sui$visite5<-as.Date(sui$visite5, "%d/%m/%Y")
sui$visite6<-as.Date(sui$visite6, "%d/%m/%Y")
sui$visite7<-as.Date(sui$visite7, "%d/%m/%Y")
sui$visite8<-as.Date(sui$visite8, "%d/%m/%Y")

```


Creer les variable sur la différence des dates



```{r}
sui<-sui%>%
  mutate(d1=visite1-Rendezvous1,
         d2=visite2-Rendezvous2,
         d3=visite3-Rendezvous3,
         d4=visite4-Rendezvous4,
         d5=visite5-Rendezvous5,
         d6=visite6-Rendezvous6,
         d7=visite7-Rendezvous7,
         d8=visite8-Rendezvous8
         )
```


-Ceux qui ont un RDV dans le futur (qui sont en attente de leur RDV) = code 999
-Ceux qui ne sont pas venus à leur RDV à partir de la date du jour = code 500


```{r}


data_date<-Sys.Date()-5

sui$d1<-as.character(sui$d1)
sui$d2<-as.character(sui$d2)
sui$d3<-as.character(sui$d3)
sui$d4<-as.character(sui$d4)
sui$d5<-as.character(sui$d5)
sui$d6<-as.character(sui$d6)
sui$d7<-as.character(sui$d7)
sui$d8<-as.character(sui$d8)

sui<-sui%>%
  mutate(d1=if_else(is.na(Rendezvous1), "9999", d1))%>%
  mutate(d1=if_else(is.na(d1) & Rendezvous1 > data_date, "999", d1))%>%
  mutate(d1=if_else(!is.na(Rendezvous1) & is.na(visite1) & Rendezvous1 < data_date, "500", d1))
    

sui<-sui%>%
  mutate(d2=if_else(is.na(Rendezvous2), "9999", d2))%>%
  mutate(d2=if_else(is.na(d2) & Rendezvous2 > data_date, "999", d2))%>%
  mutate(d2=if_else(!is.na(Rendezvous2) & is.na(visite2) & Rendezvous2 < data_date, "500", d2)) 


sui<-sui%>%
  mutate(d3=if_else(is.na(Rendezvous3), "9999", d3))%>%
  mutate(d3=if_else(is.na(d3) & Rendezvous3 > data_date, "999", d3))%>%
  mutate(d3=if_else(!is.na(Rendezvous3) & is.na(visite3) & Rendezvous3 < data_date, "500", d3))


sui<-sui%>%
  mutate(d4=if_else(is.na(Rendezvous4), "9999", d4))%>%
  mutate(d4=if_else(is.na(d4) & Rendezvous4 > data_date, "999", d4))%>%
  mutate(d4=if_else(!is.na(Rendezvous4) & is.na(visite4) & Rendezvous4 < data_date, "500", d4))


sui<-sui%>%
  mutate(d5=if_else(is.na(Rendezvous5), "9999", d5))%>%
  mutate(d5=if_else(is.na(d5) & Rendezvous2 > data_date, "999", d5))%>%
  mutate(d5=if_else(!is.na(Rendezvous5) & is.na(visite5) & Rendezvous5 < data_date, "500", d5))


sui<-sui%>%
  mutate(d6=if_else(is.na(Rendezvous6), "9999", d6))%>%
  mutate(d6=if_else(is.na(d6) & Rendezvous6 > data_date, "999", d6))%>%
  mutate(d6=if_else(!is.na(Rendezvous6) & is.na(visite6) & Rendezvous6 < data_date, "500", d6))


sui<-sui%>%
  mutate(d7=if_else(is.na(Rendezvous7), "9999", d7))%>%
  mutate(d7=if_else(is.na(d7) & Rendezvous7 > data_date, "999", d7))%>%
  mutate(d7=if_else(!is.na(Rendezvous7) & is.na(visite7) & Rendezvous7 < data_date, "500", d7))


sui<-sui%>%
  mutate(d8=if_else(is.na(Rendezvous8), "9999", d8))%>%
  mutate(d8=if_else(is.na(d8) & Rendezvous8 > data_date, "999", d8))%>%
  mutate(d8=if_else(!is.na(Rendezvous8) & is.na(visite8) & Rendezvous8 < data_date, "500", d8))



```



```{r}


sui$d1<-as.numeric(sui$d1)

sui1<- sui[(sui$d1<1000),]


nb.cols <- 10
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

sui2<-sui1%>%
mutate(d1cat=cut(d1, breaks = c(-40,0,0.5,3,120,550,1050), labels = c("Avant \nRDV","Jour J \nRDV","1-2J après \nRDV","3J+ après \nRDV", "Pas venu \nau RDV", "En attente \ndu RDV"), right = FALSE))

           
sui2<-sui2[!is.na(sui2$d1cat),]

sui3<-sui2%>%
  group_by(d1cat)%>%
  count()%>%
  mutate(suiprop=round((n/nrow(sui2))*100),
         ptext=paste0(suiprop,"%",sep="")) 

plot40<-sui3%>% 
  ggplot(aes(x=d1cat, y=n, fill=d1cat ))+
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Suivi des patients ayant une comorbidité \nselon leur date de RDV au 1er RDV (N=1317)",
       y="Nombre de cas",
       x="")+
  theme(title = element_text(size=8))+
  rotate_x_text(0)+
  geom_text(aes(label=ptext), vjust=-0.5, color="black", size=4)+
  ylim(0,900)+
  theme(axis.text=element_text(size=7))+
  scale_fill_manual(values = mycolors) 
plot40


```



```{r}

sui$d2<-as.numeric(sui$d2)

sui1<- sui[(sui$d2<1000),]


nb.cols <- 10
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

sui2<-sui1%>%
mutate(d2cat=cut(d2, breaks = c(-40,0,0.5,3,120,550,1050), labels = c("Avant \nRDV","Jour J \nRDV","1-2J après \nRDV","3J+ après \nRDV", "Pas venu \nRDV", "En attente \nRDV"), right = FALSE))

            
sui2<-sui2[!is.na(sui2$d2cat),]

sui3<-sui2%>%
  group_by(d2cat)%>%
  count()%>%
  mutate(suiprop=round((n/nrow(sui2))*100),
         ptext=paste0(suiprop,"%",sep="")) 

plot41<-sui3%>% 
  ggplot(aes(x=d2cat, y=n, fill=d2cat ))+
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Suivi des patients ayant une comorbidité \nselon leur date de RDV au 2nd RDV (N=849)",
       y="Nombre de cas",
       x="")+
  theme(title = element_text(size=8))+
  rotate_x_text(0)+
  geom_text(aes(label=ptext), vjust=-0.5, color="black", size=4)+
  ylim(0,400)+
  theme(axis.text=element_text(size=7))+
  scale_fill_manual(values = mycolors) 
plot41

```



```{r}

sui$d3<-as.numeric(sui$d3)

sui1<- sui[(sui$d3<1000),]


nb.cols <- 10
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

sui2<-sui1%>%
mutate(d3cat=cut(d3, breaks = c(-40,0,0.5,3,120,550,1050), labels = c("Avant \nRDV","Jour J \nRDV","1-2J après \nRDV","3J+ après \nRDV", "Pas venu \nRDV", "En attente \nRDV"), right = FALSE))

            
sui2<-sui2[!is.na(sui2$d3cat),]

sui3<-sui2%>%
  group_by(d3cat)%>%
  count()%>%
  mutate(suiprop=round((n/nrow(sui2))*100),
         ptext=paste0(suiprop,"%",sep="")) 

plot42<-sui3%>% 
  ggplot(aes(x=d3cat, y=n, fill=d3cat ))+
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Suivi des patients ayant une comorbidité \nselon leur date de RDV au 3ème RDV (N=433)",
       y="Nombre de cas",
       x="")+
  theme(title = element_text(size=8))+
  rotate_x_text(0)+
  geom_text(aes(label=ptext), vjust=-0.5, color="black", size=4)+
  ylim(0,225)+
  theme(axis.text=element_text(size=7))+
  scale_fill_manual(values = mycolors) 
plot42


```





```{r}


sui$d4<-as.numeric(sui$d4)

sui1<- sui[(sui$d4<1000),]


nb.cols <- 10
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

sui2<-sui1%>%
mutate(d4cat=cut(d4, breaks = c(-40,0,0.5,3,120,550,1050), labels = c("Avant \nRDV","Jour J \nRDV","1-2J après \nRDV","3J+ après \nRDV", "Pas venu \nRDV", "En attente \nRDV"), right = FALSE))

sui2<-sui2[!is.na(sui2$d4cat),]


sui3<-sui2%>%
  group_by(d4cat)%>%
  count()%>%
  mutate(suiprop=round((n/nrow(sui2))*100),
         ptext=paste0(suiprop,"%",sep="")) 

plot43<-sui3%>% 
  ggplot(aes(x=d4cat, y=n, fill=d4cat ))+
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Suivi des patients ayant une comorbidité \nselon leur date de RDV au 4ème (N=279)",
       y="Nombre de cas",
       x="")+
  theme(title = element_text(size=8))+
  rotate_x_text(0)+
  geom_text(aes(label=ptext), vjust=-0.5, color="black", size=4)+
  ylim(0,150)+
  theme(axis.text=element_text(size=7))+
  scale_fill_manual(values = mycolors) 
plot43


```


Combiner les graphs précédent en 1 seul graph

```{r}


grid.newpage()
pushViewport(viewport(layout = grid.layout(2,2)))

print(plot40, vp=viewport(layout.pos.row = 1, layout.pos.col = 1))
print(plot41, vp=viewport(layout.pos.row = 1, layout.pos.col = 2))
print(plot42, vp=viewport(layout.pos.row = 2, layout.pos.col = 1))
print(plot43, vp=viewport(layout.pos.row = 2, layout.pos.col = 2))


```



```{r}


sui$d5<-as.numeric(sui$d5)

sui1<- sui[(sui$d5<1000),]


nb.cols <- 10
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

sui2<-sui1%>%
mutate(d5cat=cut(d5, breaks = c(-40,0,0.5,3,120,550,1050), labels = c("Avant \nRDV","Jour J \nRDV","1-2J après \nRDV","3J+ après \nRDV", "Pas venu \nRDV", "En attente \nRDV"), right = FALSE))

sui2<-sui2[!is.na(sui2$d5cat),]


sui3<-sui2%>%
  group_by(d5cat)%>%
  count()%>%
  mutate(suiprop=round((n/182)*100),
         ptext=paste0(suiprop,"%",sep="")) 

plot44<-sui3%>% 
  ggplot(aes(x=d5cat, y=n, fill=d5cat ))+
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Suivi des patients ayant une comorbidité \nselon leur date de RDV au 5ème (N=182)",
       y="Nombre de cas",
       x="")+
  theme(title = element_text(size=8))+
  rotate_x_text(0)+
  geom_text(aes(label=n), vjust=-0.5, color="black", size=3.5)+
  ylim(0,100)+
  theme(axis.text=element_text(size=7))+
  scale_fill_manual(values = mycolors) 
plot44


```






```{r}


sui$d6<-as.numeric(sui$d6)

sui1<- sui[(sui$d6<1000),]


nb.cols <- 10
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

sui2<-sui1%>%
mutate(d6cat=cut(d6, breaks = c(-40,0,0.5,3,120,550,1050), labels = c("Avant \nRDV","Jour J \nRDV","1-2J après \nRDV","3J+ après \nRDV", "Pas venu \nRDV", "En attente \nRDV"), right = FALSE))

sui2<-sui2[!is.na(sui2$d6cat),]


sui3<-sui2%>%
  group_by(d6cat)%>%
  count()%>%
  mutate(suiprop=round((n/182)*100),
         ptext=paste0(suiprop,"%",sep="")) 

plot45<-sui3%>% 
  ggplot(aes(x=d6cat, y=n, fill=d6cat ))+
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Suivi des patients ayant une comorbidité \nselon leur date de RDV au 6ème (N=182)",
       y="Nombre de cas",
       x="")+
  theme(title = element_text(size=8))+
  rotate_x_text(0)+
  geom_text(aes(label=n), vjust=-0.5, color="black", size=3.5)+
  ylim(0,40)+
  theme(axis.text=element_text(size=7))+
  scale_fill_manual(values = mycolors) 
plot45




```





```{r}


sui$d7<-as.numeric(sui$d7)

sui1<- sui[(sui$d7<1000),]


nb.cols <- 10
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

sui2<-sui1%>%
mutate(d7cat=cut(d7, breaks = c(-40,0,0.5,3,120,550,1050), labels = c("Avant \nRDV","Jour J \nRDV","1-2J après \nRDV","3J+ après \nRDV", "Pas venu \nRDV", "En attente \nRDV"), right = FALSE))

sui2<-sui2[!is.na(sui2$d7cat),]


sui3<-sui2%>%
  group_by(d7cat)%>%
  count()%>%
  mutate(suiprop=round((n/17)*100),
         ptext=paste0(suiprop,"%",sep="")) 

plot45<-sui3%>% 
  ggplot(aes(x=d7cat, y=n, fill=d7cat ))+
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Suivi des patients ayant une comorbidité \nselon leur date de RDV au 7ème (N=17)",
       y="Nombre de cas",
       x="")+
  theme(title = element_text(size=8))+
  rotate_x_text(0)+
  geom_text(aes(label=n), vjust=-0.5, color="black", size=3.5)+
  ylim(0,10)+
  theme(axis.text=element_text(size=7))+
  scale_fill_manual(values = mycolors) 
plot45


```




```{r}


sui$d8<-as.numeric(sui$d8)

sui1<- sui[(sui$d8<1000),]


nb.cols <- 10
mycolors <- colorRampPalette(brewer.pal(8, "Set3"))(nb.cols)

sui2<-sui1%>%
mutate(d8cat=cut(d8, breaks = c(-40,0,0.5,3,120,550,1050), labels = c("Avant \nRDV","Jour J \nRDV","1-2J après \nRDV","3J+ après \nRDV", "Pas venu \nRDV", "En attente \nRDV"), right = FALSE))

sui2<-sui2[!is.na(sui2$d8cat),]


sui3<-sui2%>%
  group_by(d8cat)%>%
  count()%>%
  mutate(suiprop=round((n/7)*100),
         ptext=paste0(suiprop,"%",sep="")) 

plot45<-sui3%>% 
  ggplot(aes(x=d8cat, y=n, fill=d8cat ))+
  geom_col()+
  theme(legend.position = "none")+
  labs(title = "Suivi des patients ayant une comorbidité \nselon leur date de RDV au 8ème (N=7)",
       y="Nombre de cas",
       x="")+
  theme(title = element_text(size=8))+
  rotate_x_text(0)+
  geom_text(aes(label=n), vjust=-0.5, color="black", size=3.5)+
  ylim(0,5)+
  theme(axis.text=element_text(size=7))+
  scale_fill_manual(values = mycolors) 
plot45


```






